image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

do-it:
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - echo $SANITY_AUTH_TOKEN
    - SANITY_AUTH_TOKEN=$SANITY_AUTH_TOKEN yarn deploy
